import os
from dotenv import load_dotenv

load_dotenv()

LWA_APP_ID = os.environ["LWA_APP_ID"]
CLIENT_SECRET = os.environ["CLIENT_SECRET"]
AWS_ACCESS_KEY = os.environ["AWS_ACCESS_KEY"]
AWS_SECRET_KEY = os.environ["AWS_SECRET_KEY"]
ROLE_ARN = os.environ["ROLE_ARN"]

GOOGLE_SHEETS_EMAIL = os.environ["GOOGLE_SHEETS_EMAIL"]
GOOGLE_SHEETS_ID = os.environ["GOOGLE_SHEETS_ID"]

# UK
GOOGLE_WORKSHEET_NAME_UK = os.environ["GOOGLE_WORKSHEET_NAME_UK"]
REFRESH_TOKEN_UK = os.environ["REFRESH_TOKEN_UK"]

# DE
GOOGLE_WORKSHEET_NAME_DE = os.environ["GOOGLE_WORKSHEET_NAME_DE"]
REFRESH_TOKEN_DE = os.environ["REFRESH_TOKEN_DE"]

# FR
GOOGLE_WORKSHEET_NAME_FR = os.environ["GOOGLE_WORKSHEET_NAME_FR"]
REFRESH_TOKEN_FR = os.environ["REFRESH_TOKEN_FR"]

# IT
GOOGLE_WORKSHEET_NAME_IT = os.environ["GOOGLE_WORKSHEET_NAME_IT"]
REFRESH_TOKEN_IT = os.environ["REFRESH_TOKEN_IT"]

# ES
GOOGLE_WORKSHEET_NAME_ES = os.environ["GOOGLE_WORKSHEET_NAME_ES"]
REFRESH_TOKEN_ES= os.environ["REFRESH_TOKEN_ES"]

# NL
GOOGLE_WORKSHEET_NAME_NL = os.environ["GOOGLE_WORKSHEET_NAME_NL"]
REFRESH_TOKEN_NL = os.environ["REFRESH_TOKEN_NL"]

# SE
GOOGLE_WORKSHEET_NAME_SE = os.environ["GOOGLE_WORKSHEET_NAME_SE"]
REFRESH_TOKEN_SE = os.environ["REFRESH_TOKEN_SE"]

# BE
GOOGLE_WORKSHEET_NAME_BE = os.environ["GOOGLE_WORKSHEET_NAME_BE"]
REFRESH_TOKEN_BE = os.environ["REFRESH_TOKEN_BE"]